// Copyright 2021-present Etherna SA
// This file is part of Etherna Credit.
// 
// Etherna Credit is free software: you can redistribute it and/or modify it under the terms of the
// GNU Affero General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
// 
// Etherna Credit is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License along with Etherna Credit.
// If not, see <https://www.gnu.org/licenses/>.

using Etherna.CreditSystem.Areas.Api.DtoModels;
using Etherna.CreditSystem.Areas.Api.Services;
using Etherna.CreditSystem.Attributes;
using Etherna.CreditSystem.Configs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace Etherna.CreditSystem.Areas.Api.Controllers
{
    [ApiController]
    [ApiVersion("0.3")]
    [Route("api/v{api-version:apiVersion}/[controller]")]
    [Authorize(CommonConsts.ServiceInteractApiScopePolicy)]
    public class ServiceInteractController(IServiceInteractControllerService service) : ControllerBase
    {
        // Get.

        /// <summary>
        /// Get credit status for an user
        /// </summary>
        /// <param name="address">The user address</param>
        /// <returns>User credit</returns>
        [HttpGet("users/{address}/credit")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public Task<CreditDto> GetUserCreditAsync([Required] string address) =>
            service.GetUserCreditAsync(address);

        /// <summary>
        /// Get logs generated by current service with a user
        /// </summary>
        /// <param name="address">The user address</param>
        /// <param name="fromDate">Low date limit for query</param>
        /// <param name="toDate">High date limit for query</param>
        /// <response code="200">Logs list from query</response>
        [HttpGet("users/{address}/oplogs")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public Task<IEnumerable<OperationLogDto>> GetServiceOpLogsWithUserAsync(
            [Required] string address,
            DateTime? fromDate = null,
            DateTime? toDate = null) =>
            service.GetServiceOpLogsWithUserAsync(address, fromDate, toDate);

        // Put.

        /// <summary>
        /// Udpate the credit balance of an user by a given amount
        /// </summary>
        /// <param name="address">The user address</param>
        /// <param name="amount">The amount to be updated. Positive for credit, negative for debit</param>
        /// <param name="isApplied">True if credit update needs to be applied to user balance</param>
        /// <param name="reason">The update reason description</param>
        [HttpPut("users/{address}/credit/balance")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public Task RegisterBalanceUpdateAsync(
            [Required] string address,
            [Required] decimal amount,
            [Required] string reason,
            bool isApplied = true) =>
            service.RegisterBalanceUpdateAsync(address, amount, isApplied, reason);
    }
}
